### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by prasidda** [mskilab/gTrack#15]
I keep getting this error when trying to install gTrack in R 3.6.1. Any idea why? 
I was able to install and load gUtils just fine. 

> devtools::install_github('mskilab/gTrack')
Downloading GitHub repo mskilab/gTrack@master
Error: Failed to install 'gTrack' from GitHub:
  Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.

**Comment by mskilab** [comment]
Sorry - we will look into this !

**Comment by ddhb** [comment]
I got same error. what happen?

**Comment by xtYao** [comment]
@ddhb @prasidda we've moved on to R4, please let us know if this error still persists with the latest commit.
