### ISSUE TITLE
GENCODE_DIR outdated

### ISSUE THREAD

**Issue by walaj** [mskilab/gTrack#35]
It looks like GENCODE_DIR still points to mskilab.com -- is there a new place where some of the pre-computed features (like for `track.gencode`) are held?

**Comment by shihabdider** [comment]
The links should now be fixed.

**Comment by antoniakowalewski** [comment]
track.gencode() is still not working for me, returns the following error:

```Error in track.gencode() :
  Can't successfully download file from http://mskilab.com/gTrack/hg19//gencode.composite.collapsed.rds. Please check if this URL exists or if there is an issue with your internet connection

**Comment by shihabdider** [comment]
Seems like it's adding an extra slash which is messing up the fetch. It works (e.g you can try putting the following in your browser), if the slash is omitted:

`http://mskilab.com/gTrack/hg19/gencode.composite.collapsed.rds`. 

Changing the default should fix this...

**Comment by shihabdider** [comment]
Changed the default url construction code. This should now be fixed.
